language: python
python:
  - "2.7"
  - "3.4"

install:
    # update aptitude
    - sudo apt-get update -y

    - sudo apt-get install -y aptitude

    # install aptitude packages
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)

    # install python requirements
    - make setup

script:
    # finally run tests
    - make ci_test
